server:
      port: 8084
spring:
      application:
                 name: moviecatalogservice

management:
          endpoints:
                   web:
                      exposure:
                              include: "*"
#management.endpoints.jmx.exposure.include=*
#management.endpoint.health.show-details=ALWAYS
#management.endpoint.shutdown.enabled=true