server:
      port: 8085
spring:
      application:
                 name: moviecatalogservice
      cloud:
           config:
                 uri: http://localhost:8888

management:
          endpoints:
                   web:
                      exposure:
                              include: "*"
#management.endpoints.jmx.exposure.include=*
#management.endpoint.health.show-details=ALWAYS
#management.endpoint.shutdown.enabled=true